title: generic-python-creating-a-variable
hero_image: images/banner.png
description: generic-python-creating-a-variable description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: false
interests: "jokes/pranks, sports, art/design, photography, games, outside/weather/nature, space, animals, music/sound"
technologies: "scratch, python, html/css, micro:bit"
steps:
  - title: Step one
