---
title: Erstellen einer Variablen in Python
hero_image: images/banner.png
description: Erfahre, wie du eine Variable erstellen kannst
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: Erstelle eine Variable
