---
title: Criando uma variável em Python
hero_image: images/banner.png
description: Descubra como criar uma variável
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Crie uma variável
