---
title: Tworzenie zmiennej w Pythonie
hero_image: images/banner.png
description: Dowiedz się, jak utworzyć zmienną
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Stwórz zmienną
