---
title: Creare una variabile in Python
hero_image: images/banner.png
description: Scopri come creare una variabile
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Crea una variabile
